services:
  - type: web
    name: prompt-social-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: 10000
